"""
Django settings for prolifiko project.

Generated by 'django-admin startproject' using Django 1.9.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from datetime import timedelta

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)

BASE_URL = 'https://prolifiko.com'

DEBUG = False

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# Application definition

INSTALLED_APPS = [
    'wagtail.wagtailforms',
    'wagtail.wagtailredirects',
    'wagtail.wagtailembeds',
    'wagtail.wagtailsites',
    'wagtail.wagtailusers',
    'wagtail.wagtailsnippets',
    'wagtail.wagtaildocs',
    'wagtail.wagtailimages',
    'wagtail.wagtailsearch',
    'wagtail.wagtailadmin',
    'wagtail.wagtailcore',

    'modelcluster',
    'taggit',

    'app',
    'metrics',
    'home',
    'search',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'djcelery',
    'kombu.transport.django',
]

MIDDLEWARE_CLASSES = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',

    'wagtail.wagtailcore.middleware.SiteMiddleware',
    'wagtail.wagtailredirects.middleware.RedirectMiddleware',
]

ROOT_URLCONF = 'prolifiko.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(PROJECT_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.base_url',
            ],
        },
    },
]

WSGI_APPLICATION = 'prolifiko.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, 'static'),
    os.path.join(BASE_DIR, 'dist'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# Wagtail settings

WAGTAIL_SITE_NAME = "prolifiko"

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': ('%(asctime)s [%(levelname)s] %(name)s ' +
                       '%(message)s'),
            # 'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        }
    },
    'handlers': {
        'null': {
            'class': 'logging.NullHandler',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO'
        },
        'prolifiko': {
            'handlers': ['console'],
            'level': 'DEBUG',
            # 'level': 'DEBUG' if DEBUG else 'INFO'
        }
    }
}


EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = 'Bec and Chris <email@prolifiko.com>'

EMAIL_META = {
    'n1_registration': {
        'subject': "Your 5 day writing challenge – welcome!",
    },
    'n2_new_goal': {
        'subject': "1st goal set + important information",
    },
    'n3_step_1_complete': {
        'subject': "You’ve completed the toughest step – well done!",
    },
    'n4_step_2_complete': {
        'subject': "Step 2 done - now set your next step",
    },
    'n5_step_3_complete': {
        'subject': "Step 3 done - 2 steps remain",
    },
    'n6_step_4_complete': {
        'subject': "Step 4 done - just 1 step to go",
    },
    'n7_goal_complete': {
        'subject': "Way to go! You’ve finished the challenge",
    },
    'dr1': {
        'subject': 'Yikes! Did you forget to start the writing challenge?',
    },
    'dr2': {
        'subject': 'Writing challenge - get started now!',
    },
    'dr3': {
        'subject': 'Writing challenge - come back anytime',
    },
    'd1': {
        'subject': 'You’ve lost your 1st writing life',
    },
    'd2': {
        'subject': '2nd writing life lost - don’t lose another!',
    },
    'd3': {
        'subject': 'Writing challenge - try again',
    },
}

INACTIVE_TIME = int(os.environ.setdefault('PF_INACTIVE_TIME', '24'))
INACTIVE_TIME_UNIT = os.environ.setdefault('PF_INACTIVE_TIME_UNIT', 'hours')
INACTIVE_DELTA = timedelta(**{INACTIVE_TIME_UNIT: INACTIVE_TIME})

EMAIL_SEND_PERIOD = int(os.environ.setdefault('PF_EMAIL_SEND_PERIOD', '1'))
EMAIL_SEND_PERIOD_UNIT = os.environ.setdefault(
    'PF_EMAIL_SEND_PERIOD_UNIT', 'hours')
EMAIL_SEND_SCHEDULE = timedelta(**{EMAIL_SEND_PERIOD_UNIT: EMAIL_SEND_PERIOD})

BROKER_URL = 'django://'
CELERY_RESULT_BACKEND = 'djcelery.backends.database:DatabaseBackend'

CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'
CELERYBEAT_SCHEDULE = {
    'send-dr-emails': {
        'task': 'app.tasks.send_dr_emails',
        'schedule': EMAIL_SEND_SCHEDULE,
    },
    'send-d-emails': {
        'task': 'app.tasks.send_d_emails',
        'schedule': EMAIL_SEND_SCHEDULE,
    },
}

CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

os.environ.setdefault('KEEN_PROJECT_ID', '56f65f4446f9a7095a7b604b')
os.environ.setdefault('KEEN_READ_KEY', '3247d12685ca63bb6435b834cbc77b327a95' +
                      'ced379fced86e53164a410dac343602bf4d4406fec6d81a3ee1ef' +
                      '5b8e7b54af341f85a045749083803753546b7afe2ea550702dec7' +
                      'cff028a4dda82099b89dae4c28111b2859c92c9049c0be2b86')

TEST_EMAIL_ADDRESSES = [
    'mike@mbfisher.com',
    'towritetrack@gmail.com',
    'beccyevans@yahoo.co.uk',
    'revans@emeraldinsight.com',
    'airelembsay@hotmail.co.uk',
    'sally.jenkinson@gmail.com',
]

TEST_EMAIL_DOMAINS = [
    '@test.com',
    '@t.com',
    '@swarmcommunications.co.uk',
    '@prolifiko.com',
]
