# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 18:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False)),
                ('text', models.TextField(max_length=144)),
                ('start', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('end', models.DateTimeField()),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False,
                                        primary_key=True,
                                        serialize=False)),
                ('text', models.TextField(max_length=144)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('complete', models.BooleanField()),
                ('comments', models.TextField(max_length=144)),
                ('goal', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='app.Goal')),
            ],
        ),
    ]
