# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
