# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_load_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='target',
            field=models.DateField(default=datetime.datetime(2016, 10, 1, 15, 50, 53, 654904, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
