# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160413_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='goal',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='steps',
                to='app.Goal'),
        ),
    ]
