# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160425_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ('start',)},
        ),
    ]
