# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_goal_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='end',
        ),
    ]
