# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 17:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_step_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2016, 10, 1, 17, 36, 10, 443071, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
