# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_step_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
