# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160531_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='user',
            new_name='recipient',
        ),
    ]
