# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160531_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='step',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='app.Step'),
        ),
    ]
