# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160603_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ('sent',)},
        ),
    ]
