# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160603_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='end',
        ),
    ]
