# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20160706_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ('-start',)},
        ),
    ]
