# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20160809_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
