# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '9999_load_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.TextField(max_length=140),
        ),
    ]
