# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '10000_step_desc_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(
                choices=[('test', 'test'), ('auto', 'auto')],
                max_length=16),
        ),
    ]
